steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--no-cache'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=$_VITE_FIREBASE_STORAGE_BUCKET'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=$_VITE_FIREBASE_MESSAGING_SENDER_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID'
      - '--build-arg'
      - 'VITE_CLEANER_CODE=$_VITE_CLEANER_CODE'
      - '--build-arg'
      - 'VITE_VERIFY_THRESHOLD=$_VITE_VERIFY_THRESHOLD'
      - '--build-arg'
      - 'VITE_ADMIN_UID=$_VITE_ADMIN_UID'
      - '--build-arg'
      - 'VITE_GOOGLE_MAPS_API_KEY=$_VITE_GOOGLE_MAPS_API_KEY'
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '.'
images:
  - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
